# Setup
title: 데이터 구글링하시나요?
description: It's My Data Study Room!
url: https://chaaaning.github.io
avatar: /identt.jpg
paginate: 5
permalink: pretty
cover_image: /plz_wait.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
# twitter:
#   username: vszhub
#   card: summary
# logo: logo.png
social:
  name: RNCH
  links:
    # - https://twitter.com/vszhub
    - https://github.com/chaaaning
google_site_verification: xxxxx
lang: ko

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-216461603-1

# Replace this value and uncomment to enable Disqus
disqus: RNCH

# Specify the author for blog posts
author:
  name: RNCH
  url: https://github.com/chaaaning/
  email: yunjch21@gmail.com

tipue_search:
    include:
        pages: false
        collections: []
    exclude:
        files: [search.html, index.html, tags.html]
        categories: []
        tags: []


# markdown: kramdown
# kramdown:
#     highlighter: rouge
#     syntax_highlighter_opts:
#         block:
#             line_numbers: true